### PR TITLE
Feature/replace modules with aws resources

### PR DESCRIPTION
**Pull request by Stretch96**

### CODE REVIEW

**Comment by squidfunk** [comment]
This is a huge PR. Quickly skimming through the sources – does this mean this module becomes essentially obsolete? It sounds to me like deprecation is an alternative we should consider.

**Comment by Stretch96** [comment]
Yep the modules become obsolete.

However, this module still provides good defaults for setting GitHub CI (eg. the default CodeBuild project).

This module still follows the 're-usable code' idea and ensures that if there are any changes to terraform in future, we only need to change the code in this module to update it across various projects.

**Comment by squidfunk** [comment]
Okay great, I will review your PR as soon as possible. Thanks for doing all the work!

**Comment by Stretch96** [comment]
Np 👍

**Comment by hussfelt** [comment]
@squidfunk thank's for maintaining this up until now! This was an awesome module when it was needed :-) Merry Christmas! 🎄 🎅

**Pull request merged**
